"""Initial migration

Revision ID: 577cc90ac39a
Revises: ed980d8080a8
Create Date: 2026-08-17 13:31:39.091526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '577cc90ac39a'
down_revision = 'ed980d8080a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimonies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('testimonies', schema=None) as batch_op:
        batch_op.drop_column('reviewed_at')

    # ### end Alembic commands ###
