"""add missing church stats tables

Revision ID: de86162f92ff
Revises: d4e5f6a7b8c9
Create Date: 2026-08-29 10:03:53.068438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de86162f92ff'
down_revision = 'd4e5f6a7b8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_growth',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_members', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('church_stats',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('total_members', sa.Integer(), nullable=True),
    sa.Column('total_men', sa.Integer(), nullable=True),
    sa.Column('total_women', sa.Integer(), nullable=True),
    sa.Column('total_children', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Uuid(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_records',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.Uuid(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_records')
    op.drop_table('church_stats')
    op.drop_table('member_growth')
    # ### end Alembic commands ###
